### ISSUE TITLE
vai ficar "lento"

### ISSUE THREAD

**Issue by marioidival** [cassiobotaro/fast_scraping_asyncio#1]
https://github.com/MagicStack/uvloop

**Comment by cassiobotaro** [comment]
The goal is just to show how to do something asynchronous, not be the fastest.

**Comment by marioidival** [comment]
O
Kay
![2017-09-04-101425_338x45_scrot](https://user-images.githubusercontent.com/1129263/30028049-d7dfec50-9159-11e7-820a-3aed243823e0.png)
